version: '1'

services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=api-user
      - POSTGRES_PASSWORD=Gr4viP3t#ApIUs3rP@ssW0rD
      - POSTGRES_DB=foodtosavedev
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    networks:
      - backend-network

  redis:
    image: redis
    ports:
      - "6379:6379"
    networks:
      - backend-network

  api:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - POSTGRES_USER=api-user
      - POSTGRES_PASSWORD=Gr4viP3t#ApIUs3rP@ssW0rD
      - POSTGRES_DB=foodtosavedev
      - POSTGRES_HOST=postgres
      - REDIS_HOST=redis
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - redis
    networks:
      - backend-network

networks:
  backend-network:
    driver: bridge
